// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nogizaka.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseType) Reset()         { *m = ResponseType{} }
func (m *ResponseType) String() string { return proto.CompactTextString(m) }
func (*ResponseType) ProtoMessage()    {}
func (*ResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_nogizaka_d007a3d706504a78, []int{0}
}
func (m *ResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseType.Unmarshal(m, b)
}
func (m *ResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseType.Marshal(b, m, deterministic)
}
func (dst *ResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseType.Merge(dst, src)
}
func (m *ResponseType) XXX_Size() int {
	return xxx_messageInfo_ResponseType.Size(m)
}
func (m *ResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseType proto.InternalMessageInfo

type RequestType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestType) Reset()         { *m = RequestType{} }
func (m *RequestType) String() string { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()    {}
func (*RequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_nogizaka_d007a3d706504a78, []int{1}
}
func (m *RequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestType.Unmarshal(m, b)
}
func (m *RequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestType.Marshal(b, m, deterministic)
}
func (dst *RequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestType.Merge(dst, src)
}
func (m *RequestType) XXX_Size() int {
	return xxx_messageInfo_RequestType.Size(m)
}
func (m *RequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestType.DiscardUnknown(m)
}

var xxx_messageInfo_RequestType proto.InternalMessageInfo

type Member struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Generation           int32    `protobuf:"varint,4,opt,name=Generation,proto3" json:"Generation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_nogizaka_d007a3d706504a78, []int{2}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Member) GetGeneration() int32 {
	if m != nil {
		return m.Generation
	}
	return 0
}

func init() {
	proto.RegisterType((*ResponseType)(nil), "proto.ResponseType")
	proto.RegisterType((*RequestType)(nil), "proto.RequestType")
	proto.RegisterType((*Member)(nil), "proto.Member")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NogizakaClient is the client API for Nogizaka service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NogizakaClient interface {
	ListMember(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (Nogizaka_ListMemberClient, error)
	AddMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*ResponseType, error)
}

type nogizakaClient struct {
	cc *grpc.ClientConn
}

func NewNogizakaClient(cc *grpc.ClientConn) NogizakaClient {
	return &nogizakaClient{cc}
}

func (c *nogizakaClient) ListMember(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (Nogizaka_ListMemberClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Nogizaka_serviceDesc.Streams[0], "/proto.Nogizaka/ListMember", opts...)
	if err != nil {
		return nil, err
	}
	x := &nogizakaListMemberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Nogizaka_ListMemberClient interface {
	Recv() (*Member, error)
	grpc.ClientStream
}

type nogizakaListMemberClient struct {
	grpc.ClientStream
}

func (x *nogizakaListMemberClient) Recv() (*Member, error) {
	m := new(Member)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nogizakaClient) AddMember(ctx context.Context, in *Member, opts ...grpc.CallOption) (*ResponseType, error) {
	out := new(ResponseType)
	err := c.cc.Invoke(ctx, "/proto.Nogizaka/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NogizakaServer is the server API for Nogizaka service.
type NogizakaServer interface {
	ListMember(*RequestType, Nogizaka_ListMemberServer) error
	AddMember(context.Context, *Member) (*ResponseType, error)
}

func RegisterNogizakaServer(s *grpc.Server, srv NogizakaServer) {
	s.RegisterService(&_Nogizaka_serviceDesc, srv)
}

func _Nogizaka_ListMember_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NogizakaServer).ListMember(m, &nogizakaListMemberServer{stream})
}

type Nogizaka_ListMemberServer interface {
	Send(*Member) error
	grpc.ServerStream
}

type nogizakaListMemberServer struct {
	grpc.ServerStream
}

func (x *nogizakaListMemberServer) Send(m *Member) error {
	return x.ServerStream.SendMsg(m)
}

func _Nogizaka_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Member)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NogizakaServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Nogizaka/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NogizakaServer).AddMember(ctx, req.(*Member))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nogizaka_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Nogizaka",
	HandlerType: (*NogizakaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMember",
			Handler:    _Nogizaka_AddMember_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMember",
			Handler:       _Nogizaka_ListMember_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nogizaka.proto",
}

func init() { proto.RegisterFile("nogizaka.proto", fileDescriptor_nogizaka_d007a3d706504a78) }

var fileDescriptor_nogizaka_d007a3d706504a78 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x37, 0xdd, 0x0f, 0x76, 0x47, 0xb7, 0x87, 0xf1, 0x12, 0x7a, 0x90, 0xd2, 0x53, 0x4f,
	0x8b, 0xba, 0x4f, 0xa0, 0x17, 0x29, 0x68, 0x0f, 0xc1, 0x17, 0x48, 0xc9, 0x60, 0x83, 0x34, 0xa9,
	0x49, 0x3c, 0xd4, 0xa7, 0x17, 0xd2, 0x50, 0xea, 0x69, 0xe6, 0xff, 0x9b, 0xaf, 0xff, 0x40, 0x6e,
	0xec, 0xa7, 0xfe, 0x95, 0x5f, 0xf2, 0x32, 0x3a, 0x1b, 0x2c, 0xee, 0x63, 0xa8, 0x72, 0xb8, 0x15,
	0xe4, 0x47, 0x6b, 0x3c, 0x7d, 0x4c, 0x23, 0x55, 0x67, 0xb8, 0x11, 0xf4, 0xfd, 0x43, 0x3e, 0x44,
	0xd9, 0xc3, 0xe1, 0x9d, 0x86, 0x8e, 0x1c, 0xe6, 0x90, 0x35, 0x8a, 0xb3, 0x92, 0xd5, 0x5b, 0x91,
	0x35, 0x0a, 0x11, 0x76, 0xad, 0x1c, 0x88, 0x67, 0x25, 0xab, 0x4f, 0x22, 0xe6, 0x58, 0xc0, 0xf1,
	0x45, 0xbb, 0xd0, 0x2b, 0x39, 0xf1, 0x6d, 0xe4, 0x8b, 0xc6, 0x7b, 0x80, 0x57, 0x32, 0xe4, 0x64,
	0xd0, 0xd6, 0xf0, 0x5d, 0xc9, 0xea, 0xbd, 0x58, 0x91, 0x27, 0x07, 0xc7, 0x36, 0x39, 0xc4, 0x2b,
	0xc0, 0x9b, 0xf6, 0x21, 0x5d, 0xc6, 0xd9, 0xf1, 0x65, 0xe5, 0xab, 0x38, 0x27, 0x36, 0xb7, 0x54,
	0x9b, 0x07, 0x86, 0x8f, 0x70, 0x7a, 0x56, 0x2a, 0xcd, 0xfc, 0xaf, 0x17, 0x77, 0xcb, 0x8a, 0xd5,
	0xab, 0x9b, 0xee, 0x10, 0xe9, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x0f, 0x24, 0xe5, 0x1c,
	0x01, 0x00, 0x00,
}
